kontiki:
  amqp:
    url: amqp://guest:guest@localhost/
  heartbeat:
    interval: 5
  peers:
    inventory: Inventory

logging:
  directory: logs
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      maxBytes: 10485760
      backupCount: 5
  root:
    handlers: [file]
    level: INFO
